DROP TABLE IF EXISTS COMMENTS;

CREATE TABLE COMMENTS (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  COMMENT VARCHAR(2000) NOT NULL,
  TIME DATE NOT NULL
);

DROP TABLE IF EXISTS NOTIFICATION;

CREATE TABLE NOTIFICATION (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    COMMENT_ID INT NOT NULL,
    TIME DATE NOT NULL,
    DELIVERED BOOLEAN NOT NULL
)